name: Build for native architecture

on: [ push, pull_request ]

jobs:
  nativebuild:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build containers
      run: make -f Makefile.all container
